services:
  quasar-app:
    build:
      context: ./dashboard-frontend       # Path to your Quasar project
      dockerfile: Dockerfile
    ports:
      - "9000:9000"           # Map Quasar container port 9000 to host port 9000
    volumes:
      - ./dashboard-frontend:/app         # Mount local Quasar code (optional, for live development)
    networks:
      - app-network

  mysql-db:
    build:
      context: ./mysql-db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: health_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"  # Map MySQL's default port 3306 to 7000 on the host
    volumes:
      - ./mysql-db/init-scripts:/docker-entrypoint-initdb.d  # Mount init-scripts directory
    networks:
      - app-network

  mysqlconnector-app:
    build:
      context: ./mysqlconnector   # Path to your Spring Boot project
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"           # Expose Spring Boot API on port 8080
    volumes:
      - ./mysqlconnector:/app     # Mount local Spring Boot code (optional, for live development)
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/health_db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge